# Generated by Django 4.2.11 on 2024-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('prduct_pic', models.ImageField(upload_to='')),
                ('product_price', models.FloatField()),
            ],
        ),
    ]
