# Generated by Django 4.2.11 on 2024-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='empty', max_length=20),
        ),
    ]
