# Generated by Django 4.2.11 on 2024-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0003_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prduct_pic',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
