# Generated by Django 4.2.11 on 2024-03-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0004_alter_product_prduct_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prduct_pic',
            field=models.ImageField(upload_to='static/products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='Others', max_length=20),
        ),
    ]
