# Generated by Django 4.2.11 on 2024-03-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0005_alter_product_prduct_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prduct_pic',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
