# Generated by Django 4.2.11 on 2024-03-28 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0007_alter_product_prduct_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
