# Generated by Django 4.2.11 on 2024-03-28 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0008_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='')),
                ('pprice', models.FloatField()),
                ('pcategory', models.CharField(default='Others', max_length=20)),
            ],
        ),
    ]
