# Generated by Django 4.2.11 on 2024-04-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0010_user_islogged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
