# Generated by Django 4.2.11 on 2024-05-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0011_alter_product_pimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
