# Generated by Django 4.2.11 on 2024-05-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toymodule', '0014_alter_product_pimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pimage',
            field=models.ImageField(blank=True, default='picture.png', null=True, upload_to=''),
        ),
    ]
